<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>DogfighterAD.SysvolWorker</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DogfighterAD.Collectors.ActiveDirectory\DogfighterAD.Collectors.ActiveDirectory.csproj" />
  </ItemGroup>
</Project>
