<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DogfighterAD.Domain\DogfighterAD.Domain.csproj" />
    <ProjectReference Include="..\..\src\DogfighterAD.Application\DogfighterAD.Application.csproj" />
    <ProjectReference Include="..\..\src\DogfighterAD.Collectors.ActiveDirectory\DogfighterAD.Collectors.ActiveDirectory.csproj" />
    <ProjectReference Include="..\..\src\DogfighterAD.Serialization\DogfighterAD.Serialization.csproj" />
  </ItemGroup>
</Project>
